CREATE TABLE users (
    id uuid NOT NULL,
    email varchar(255),
    nickname varchar(50) NOT NULL,
    profile_image text,
    bio varchar(500),
    provider varchar(255) NOT NULL,
    provider_id varchar(255) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_provider_provider_id UNIQUE (provider, provider_id),
    CONSTRAINT chk_users_provider CHECK (provider IN ('KAKAO', 'NAVER'))
);

CREATE TABLE categories (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(50) NOT NULL,
    display_order integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uq_categories_name UNIQUE (name)
);

CREATE TABLE style_presets (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(50) NOT NULL,
    description varchar(200),
    thumbnail_url text,
    prompt_prefix text NOT NULL,
    display_order integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT pk_style_presets PRIMARY KEY (id),
    CONSTRAINT uq_style_presets_name UNIQUE (name)
);

CREATE TABLE layout_templates (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(50) NOT NULL,
    description varchar(200),
    thumbnail_url text,
    css_class varchar(100),
    layout_config jsonb NOT NULL,
    display_order integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT pk_layout_templates PRIMARY KEY (id),
    CONSTRAINT uq_layout_templates_name UNIQUE (name)
);

CREATE TABLE fonts (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(100) NOT NULL,
    font_family varchar(100) NOT NULL,
    font_url text,
    category varchar(50),
    is_active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT pk_fonts PRIMARY KEY (id),
    CONSTRAINT uq_fonts_name UNIQUE (name)
);

CREATE TABLE books (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    title varchar(200) NOT NULL,
    description text,
    category_id integer,
    style_preset_id integer,
    layout_template_id integer,
    font_id integer,
    price integer,
    cover_image_url text,
    author_name varchar(100),
    target_page_count integer,
    font_size integer,
    font_color varchar(7),
    status varchar(255) NOT NULL,
    visibility varchar(255) NOT NULL,
    share_link_token varchar(64),
    attempt_number integer NOT NULL,
    last_saved_at timestamp(6) without time zone,
    published_at timestamp(6) without time zone,
    view_count bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT pk_books PRIMARY KEY (id),
    CONSTRAINT uq_books_share_link_token UNIQUE (share_link_token),
    CONSTRAINT chk_books_status CHECK (status IN ('DRAFT', 'IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT chk_books_visibility CHECK (visibility IN ('PRIVATE', 'LINK_SHARED', 'PUBLIC', 'PAID'))
);

CREATE TABLE pages (
    id uuid NOT NULL,
    book_id uuid NOT NULL,
    page_number integer NOT NULL,
    raw_text text,
    refined_text text,
    image_url text,
    image_source varchar(255),
    image_prompt text,
    layout_override jsonb,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT pk_pages PRIMARY KEY (id),
    CONSTRAINT uq_pages_book_page_number UNIQUE (book_id, page_number),
    CONSTRAINT fk_pages_book FOREIGN KEY (book_id) REFERENCES books (id),
    CONSTRAINT chk_pages_image_source CHECK (image_source IN ('AI_TEXT_GENERATED', 'AI_IMAGE_ANALYZED', 'USER_UPLOADED'))
);

CREATE TABLE characters (
    id uuid NOT NULL,
    book_id uuid NOT NULL,
    name varchar(100) NOT NULL,
    description text,
    reference_image_url text,
    prompt_fragment text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT pk_characters PRIMARY KEY (id),
    CONSTRAINT fk_characters_book FOREIGN KEY (book_id) REFERENCES books (id)
);

CREATE TABLE page_characters (
    character_id uuid NOT NULL,
    page_id uuid NOT NULL,
    CONSTRAINT pk_page_characters PRIMARY KEY (character_id, page_id),
    CONSTRAINT fk_page_characters_character FOREIGN KEY (character_id) REFERENCES characters (id),
    CONSTRAINT fk_page_characters_page FOREIGN KEY (page_id) REFERENCES pages (id)
);

CREATE TABLE text_refinement_logs (
    id uuid NOT NULL,
    page_id uuid NOT NULL,
    input_text text NOT NULL,
    output_text text NOT NULL,
    refinement_type varchar(50),
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT pk_text_refinement_logs PRIMARY KEY (id)
);

CREATE TABLE image_generation_logs (
    id uuid NOT NULL,
    page_id uuid NOT NULL,
    prompt_used text NOT NULL,
    style_preset_id integer,
    source_type varchar(255) NOT NULL,
    source_image_url text,
    result_image_url text NOT NULL,
    is_selected boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT pk_image_generation_logs PRIMARY KEY (id),
    CONSTRAINT chk_image_generation_logs_source_type CHECK (source_type IN ('AI_TEXT_GENERATED', 'AI_IMAGE_ANALYZED'))
);

CREATE TABLE cover_generation_logs (
    id uuid NOT NULL,
    book_id uuid NOT NULL,
    title_text varchar(200) NOT NULL,
    author_text varchar(100),
    style_preset_id integer,
    prompt_used text,
    result_image_url text NOT NULL,
    is_selected boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT pk_cover_generation_logs PRIMARY KEY (id)
);

CREATE TABLE auto_save_snapshots (
    id uuid NOT NULL,
    book_id uuid NOT NULL,
    snapshot_data jsonb NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT pk_auto_save_snapshots PRIMARY KEY (id)
);

CREATE TABLE banners (
    id uuid NOT NULL,
    title varchar(200) NOT NULL,
    image_url text NOT NULL,
    link_url text,
    display_order integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT pk_banners PRIMARY KEY (id)
);

CREATE TABLE reviews (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    book_id uuid NOT NULL,
    rating integer NOT NULL,
    content varchar(500),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT pk_reviews PRIMARY KEY (id),
    CONSTRAINT uq_reviews_user_book UNIQUE (user_id, book_id)
);

CREATE TABLE reports (
    id uuid NOT NULL,
    reporter_id uuid NOT NULL,
    book_id uuid NOT NULL,
    book_title varchar(255) NOT NULL,
    reason varchar(255) NOT NULL,
    detail varchar(500),
    status varchar(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT pk_reports PRIMARY KEY (id),
    CONSTRAINT chk_reports_reason CHECK (reason IN ('SPAM', 'INAPPROPRIATE', 'COPYRIGHT', 'OTHER')),
    CONSTRAINT chk_reports_status CHECK (status IN ('PENDING', 'RESOLVED', 'DISMISSED'))
);

CREATE TABLE book_likes (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    book_id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT pk_book_likes PRIMARY KEY (id),
    CONSTRAINT uq_book_likes_user_book UNIQUE (user_id, book_id)
);

CREATE TABLE author_follows (
    id uuid NOT NULL,
    follower_id uuid NOT NULL,
    author_id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT pk_author_follows PRIMARY KEY (id),
    CONSTRAINT uq_author_follows_follower_author UNIQUE (follower_id, author_id)
);

CREATE INDEX idx_author_follows_author ON author_follows (author_id);

CREATE TABLE purchases (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    book_id uuid NOT NULL,
    price integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT pk_purchases PRIMARY KEY (id),
    CONSTRAINT uq_purchases_user_book UNIQUE (user_id, book_id)
);

CREATE TABLE reading_progresses (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    book_id uuid NOT NULL,
    last_read_page_number integer NOT NULL,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT pk_reading_progresses PRIMARY KEY (id),
    CONSTRAINT uq_reading_progresses_user_book UNIQUE (user_id, book_id)
);

CREATE TABLE user_reading_goals (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    goal_year integer NOT NULL,
    goal_month integer NOT NULL,
    target_count integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT pk_user_reading_goals PRIMARY KEY (id),
    CONSTRAINT uq_user_reading_goals_user_year_month UNIQUE (user_id, goal_year, goal_month)
);
